In [1]:
import time
import cupy as cp
import numpy as np
from PIL import Image

In [4]:
def image_get_array():
    image = Image.open('image.tif')
    image_array = np.array(image)
    return image_array
    
def fft_python(image_array):
    return np.fft.rfft2(image_array)

def fft_gpu(image_array):
    return cp.fft.rfft2(image_array)

In [6]:
def main():
    print("Program starts.")
    image_array_cpu = image_get_array()
    image_array_gpu = cp.asarray(image_array_cpu)
    print("The image array is:")
    print(image_array_cpu)

    time_start = time.time()
    image_array_fft = fft_python(image_array_cpu)
    time_stop = time.time()
    print("Time taken for execution of the FFT in Python is: ", 
            time_stop - time_start, "s")

    time_start = time.time()
    image_array_fft = fft_gpu(image_array_gpu)
    time_stop = time.time()
    print("Time taken for first execution of the FFT on the GPU is: ", 
            time_stop - time_start, "s")

    time_start = time.time()
    image_array_fft = fft_gpu(image_array_gpu)
    time_stop = time.time()
    print("Time taken for second execution of the FFT on the GPU is: ", 
            time_stop - time_start, "s")

    return 0
    
main()

Program starts.
The image array is:
[[ 87  72  68 ...  98 121 149]
 [ 57  65  75 ...  69 128 102]
 [ 53  62  93 ... 105 107  98]
 ...
 [ 99 129 126 ... 100 116 115]
 [144 140 159 ... 131 101  97]
 [123 144 143 ...  95  98  91]]
<class 'numpy.ndarray'>
Time taken for execution of the FFT in Python is:  0.00997781753540039 s


TypeError: an integer is required